### ISSUE TITLE
Compilation fails with 5.0.1 works fine with 4.12.7 - MSW

### ISSUE THREAD

**Issue by grumpy235** [utelle/wxsqlite3#133]
I am compiling mmex with 5.0.1 (I think you may have contributed to this application in the past) and it fails with a bunch of errors the first of which is as follows..

`11>D:\Projects\mmex_master\src\table\_TableBase.h(40,28): error C2061: syntax error: identifier 'wxSQLite3ResultSet'
11>  (compiling source file '../../src/util/mmCalcPopup.cpp')

11>D:\Projects\mmex_master\src\table\_TableBase.h(43,28): error C2061: syntax error: identifier 'wxSQLite3ResultSet'
11>  (compiling source file '../../src/util/mmCalcPopup.cpp')

11>D:\Projects\mmex_master\src\table\_TableBase.h(43,10): error C2535: 'void TableBase::get_select_result(void)': member function already defined or declared
11>  (compiling source file '../../src/util/mmCalcPopup.cpp')
11>      D:\Projects\mmex_master\src\table\_TableBase.h(40,10):
11>      see declaration of 'TableBase::get_select_result'`

All is well when compiled with 4.12.7

The live mmex source is using 4.9.1 so is a bit behind and my method of updating wxsqlite3 is to

Download the git master for mmex

cd /d D:\Projects\mmex_master\3rd\wxsqlite3
git status

HEAD detached at 7bbd8a15
nothing to commit, working tree clean

git merge tags/v5.0.1

This has worked for years so not sure where the problem lies.

Am I missing something new in 5.0.1, is it a bug in mmex or 5.0.1 or just my lack of understanding of modern ways of compiling/source management?

I am not a developer, I just use this project to try and teach myself C++ in my retirement and to keep the grey cells active!

**Comment by utelle** [comment]
> I am compiling mmex with 5.0.1 (I think you may have contributed to this application in the past) and it fails with a bunch of errors the first of which is as follows..

This is **not** surprising. **Version 5.x** is a major update and is **not** source-code compatible with version **4.x**. Please read the [5.0.0 release notes](https://github.com/utelle/wxsqlite3/releases/tag/v5.0.0). 

**wxSQLite3** is a rather old component, roughly 20 years. And it became time to modernize it (see [Modern C++ Interface](https://utelle.github.io/wxsqlite3/docs/5.x/features.html)). Unfortunately, that comes at a price: the source code has to be adapted to the new version. A short [migration guide](https://utelle.github.io/wxsqlite3/docs/5.x/migration.html) is available.

> All is well when compiled with 4.12.7

For the time being you can stay with version **4.12.7**. In the repository the **4.x** version moved to branch [4.x](https://github.com/utelle/wxsqlite3/tree/4.x). Version **4.x** will still get maintenance for some time - I have not fixed an _End of Life_ date for **4.x** yet.

> The live mmex source is using 4.9.1 so is a bit behind

It's certainly a good idea to update to a more recent version.

> and my method of updating wxsqlite3 is to
> 
> Download the git master for mmex
> 
> cd /d D:\Projects\mmex_master\3rd\wxsqlite3 git status
> 
> HEAD detached at [7bbd8a1](https://github.com/utelle/wxsqlite3/commit/7bbd8a15f9fc0fdb81e3421a0fab90a63a6f0461) nothing to commit, working tree clean
> 
> git merge tags/v5.0.1

Stay with **4.12.7**, unless you are willing to adjust _mmex_'s source code to the new version **5.x**.

Besides that there is no reason to start with version 4.9.1 and merge a later tag. You could check out the repository at the tag of the version you want to use similar to

```
git fetch --tags
git checkout v4.12.7
```

> Am I missing something new in 5.0.1, is it a bug in mmex or 5.0.1 or just my lack of understanding of modern ways of compiling/source management?

See my comments above.

> I am not a developer, I just use this project to try and teach myself C++ in my retirement and to keep the grey cells active!

Welcome to the club! 😃

**Comment by grumpy235** [comment]
Thanks Ulrich,
After 40+ years in mainframe IT, you would think I would read the documentation before asking an obvious question. 😠 
I found the readme link just a few minutes ago and the migration guide will come in useful. I'll make sure the real developers on the project are aware of these.
