### ISSUE TITLE
Bug to use under Mac OS?

### ISSUE THREAD

**Issue by liaoxuewei** [utelle/wxsqlite3#53]
I use this qt plugin in order to use CipherSqlite https://github.com/devbean/QtCipherSqlitePlugin, it work good under android and windows, but not under mac os, when i specifying cipher algorithm to chacha20.

I've tracked the problem to call sqlite3_key=>
0   libsystem_kernel.dylib        	0x00007fff97612452 __syscall + 10  =>syscall(SYS_getentroy, ...)
1   libsqlitecipher.dylib         	0x0000000111b92513 entropy + 51
2   libsqlitecipher.dylib         	0x0000000111b92413 chacha20_rng + 243
3   libsqlitecipher.dylib         	0x0000000111cdf3d1 GenerateKeyChaCha20Cipher + 97
4   libsqlitecipher.dylib         	0x0000000111b96d11 sqlite3CodecAttach + 1729

get an error:bad system call
But I can't solve it in depth. Any body can help me?

**Comment by utelle** [comment]
Unfortunately, I don't have acces to a Mac OS X system, so that I can't test it for myself.

Obviously it has something to do with generating random data and invoking the entropy system call. Could you please tell which Mac OS X version you are using? Maybe this system call is not available for all versions.

**Comment by liaoxuewei** [comment]
Mac OS X 10.11, Error in calling syscall(SYS_getentroy, ...)
I don't think it's a big problem to call parameters. It's supposed to be a function of the operating system, but I don't know why it crashes.

**Comment by utelle** [comment]
Unfortunately, I have no idea why this system call crashes on your Mac OS X 10.11 system. Did you compile the binary on the same system?

What I can tell is that it works flawlessly on Mac OS X 10.13.3 (see [wxSQLite3 Travis CI](https://travis-ci.org/utelle/wxsqlite3/jobs/534272114) under the headings _Build system information_ and _Testing_).

**Comment by liaoxuewei** [comment]
Thanks, Maybe my system is not installed well enough.

**Comment by liaoxuewei** [comment]
I just saw you add a build test for Mac OS 10.11? Can you see the result later? :)

**Comment by utelle** [comment]
Yes, I added a CI test for OS X 10.11 to check whether your issue can be reproduced. However, it can't. See [wxSQLite3 Travis CI for OS X 10.11](https://travis-ci.org/utelle/wxsqlite3/jobs/540626569).

Sorry, I don't have a clue what might go wrong on your system and how to track it down.

**Comment by liaoxuewei** [comment]
Thank you very much for what you have done!
I think there is something wrong with my development environment. Maybe I should think about other solutions myself.

**Comment by utelle** [comment]
You are welcome.

Please let me know if you find out what causes the problem for you. Thanks.

**Comment by liaoxuewei** [comment]
OK.

**Comment by utelle** [comment]
By searching a bit I found [this](https://github.com/pyca/cryptography/issues/3332), indicating that the underlying functionality for getting entropy is only available on Mac OS X 10.12 or higher. On the other hand Travis CI for wxSQLite3 works properly on Mac OS X 10.11, as you saw.

**wxSQLite3** implements a fallback if invoking `syscall(SYS_getentropy ...)` fails with a return code. But if it crashes as in your case there is nothing **wxSQLite3** can do.

**Comment by liaoxuewei** [comment]
I don't quite understand why entropy works only in Mac OS X 10.12 or higher, and your Mac OS X 10.11 works.

If entropy is only valid in MacOS X 10.12 or higher, does it mean that accessing Invalid function addresses causes crashes?

**Comment by utelle** [comment]
I don't know much about Mac OS X unfortunately. The symbol `SYS_getentropy` seems to be defined, even on OS X 10.11, although a method/function `getentropy` seems not to be implemented on that platform. I would have expected that `sycall(SYS_getentropy ...)` would simply return with a return code under these circumstances and thus the fallback implemented in wxSQLite3 would be used. Why invoking `syscall` works on Travis CI, but crashes on your system, I really don't know.

**Comment by liaoxuewei** [comment]
I made a test application and called the code mentioned above. As a result, the application crashed, and I did not track the cause further.

In addition, I am curious about the situation that if my SQLite database was generated in Windows before, it would be normal to use chacha20 encryption algorithm and attach it to other main database through ATTACH DATABASE script. However, when I used the same encryption algorithm in Max OS to create the database, the crash problem mentioned earlier appeared. Which has been discussed above.

Strangely, it's all Chacha 20 algorithms. Why do it need to call that code when creating a database, but ATTACH DATABASE doesn't?

Note: I didn't read all the code in detail.

**Comment by liaoxuewei** [comment]
What I want to say is, is that code necessary?

In addition, does the entropy function have to call the operating system? Is there any other implementation? --Operating system independent

**Comment by liaoxuewei** [comment]
Looking back at the code, if the call fails, it will continue to call read_urandom. Can we call read_urandom directly? What are the two differences?

Some relevant information is also found here, but not very well understood. :)
https://github.com/python/cpython/commit/01bdbad3e951014c58581635b94b22868537901c

**Comment by utelle** [comment]
Using the random number generator of the operating system is more secure than using a pseudo random number generator. `read_urandom` requires the use of file handles, which is more likely to fail than `getentropy`. However, I will evaluate whether there are other options to handle generating random bytes.

The implementation of the **ChaCha20** encryption scheme in **wxSQLite3** is based on [**sqleet**](https://github.com/resilar/sqleet). It would be nice if you could check whether **sqleet** shows the same or similar behaviour (bad system call) on your system. Thanks in advance.

**Comment by liaoxuewei** [comment]
I use the following website to adjust the code, it seems that this problem has been solved. Would you like to see if it is appropriate? I have already pushed the request.
https://github.com/pyca/cryptography/pull/3841
There are other two modifications that I think might be bug.

**Comment by utelle** [comment]
I added a comment to your PR #56. As mentioned there, I'd like to discuss this `getentropy` issue with @resilar, because finding a common solution would help in the future to maintain compatibility with **sqleet**.

**Comment by resilar** [comment]
I'm not a Mac guy either, but [Homebrew/homebrew-core#3727](https://github.com/Homebrew/homebrew-core/issues/3727) suggests a build misconfiguration:

>When building on OS X 10.11 with Xcode 8 against the macOS 10.12 SDK, you'll see the symbols added in macOS 10.12 e.g. clock_gettime and getentropy. ... The built products will then fail with dynamic linker errors at runtime because the symbols aren't available on the 10.11 host system.

This would explain why the code works on Travis (because it is building correctly against the MacOS 10.11 SDK). @liaoxuewei I do not know what IDE or build environment you are using, but can you verify that it is using 10.11 SDK properly?

Despite this being a rather common issue for Mac OS X 10.11 users (at least according to Google), I'd still prefer not to workaround the issue by changing the code. The `getentropy` fix in PR #56 is shaky and could cause other problmes (what if `SYS_getentropy` is defined but `getentropy` isn't? or if `getentropy` is defined as a macro?)

**Comment by utelle** [comment]
@resilar thanks for your comments. 

Since the current code works on Travis for Mac OS X 10.11, I'm reluctant to apply any questionable fixes. However, if it were possible to reliably detect the OS X version, one could call `read_urandom(buf, n)` immediately for Mac OS X 10.11 or below instead of trying to call `syscall(SYS_getentropy, buf, n)` first. However, if symbol `SYS_getentropy` is defined (as it seems to be the case for Mac OS X 10.11), calling `syscall(SYS_getentropy, buf, n)` should actually do no harm.

**Comment by resilar** [comment]
> if symbol SYS_getentropy is defined (as it seems to be the case for Mac OS X 10.11), calling syscall(SYS_getentropy, buf, n) should actually do no harm.

`SYS_getentropy` & `getentropy` were introduced in OS X 10.12. Mac OS X 10.11 does not include them. I'm guessing that @liaoxuewei compiles against OS X 10.12 headers (SDK) on a 10.11 system. In this case `syscall(SYS_getentropy, buf, n)` compiles fine but crashes at run-time because Mac OS X 10.11 does not implement the syscall.

In general case though, calling `call(SYS_getentropy, buf, n)` should be safe if `SYS_getentropy` is defined (assuming sane build configuration without version mismatches).

**Comment by liaoxuewei** [comment]
It's "Command Line Tools macOS 10.11 for Xcode 8.2" that I downloaded. Maybe that's the reason for the problem?
@resilar

**Comment by utelle** [comment]
I have to repeat that I don't know much about Mac OS X. However, looking at this [Mac OS X 10.11 related issue elsewhere](https://github.com/Homebrew/brew/issues/972#issuecomment-248973142) (talking among other things about SDK incompatibilities) I get the impression that you could easily have some sort of mixup in your development environment.

Fact is that `getentropy` resp `SYS_getentropy` is not available on Mac OS X 10.11 and below. As I saw on Travis CI the **sqleet** resp **wxSQLite3** code worked properly on Mac OS X 10.11 with Xcode8. Therefore my guess is that your build most likely references the wrong SDK (not suitable for Mac OS X 10.11).

**Comment by liaoxuewei** [comment]
Maybe for the time being, I'll use the version I've maintained.

**Comment by utelle** [comment]
In your situation I would first verify that your build is actually referencing the correct SDK. As I see it Xcode 8 comes with different SDKs of which not all are compatible with OS X 10.11. Make sure that you compile and link against the right SDK.

Identifying the real cause of the problem in your environment would be far better than applying an obscure fix. Just my 2 ct.

**Comment by liaoxuewei** [comment]
The real reason I understand has been found, but I don't want to deal with it now, for example, maybe I can download the lower version of xcode, but it takes a lot of time. After all, it doesn't seem to have any particular impact now. I plan to use my own version temporarily. I read that the method of __attribute((weak_import)) should be feasible, the worst case. The read_urandom function is also used, so it doesn't feel too much of a problem, and it will be dealt with later if necessary.
Thanks.

**Comment by utelle** [comment]
I don't think you have to download an older version of Xcode. The only thing you have to make sure is that a matching SDK is selected when compiling for OS X 10.11. Maybe it is enough to select the right deployment target, but I really don't know for sure, because I have no OS X resp Xcode experience.

**Comment by liaoxuewei** [comment]
I'm not sure if it's MacOS SDK 10.12, but it does have /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk
in my os?

**Comment by utelle** [comment]
If your target platform is MacOSX 10.11 it is most likely not a good idea to compile and link against the MacOSX10.12 SDK. Do you have other SDKs in your path `/Library/Developer/CommandLineTools/SDKs`?

Maybe [this](https://github.com/google/honggfuzz/issues/90) helps a bit ... like checking the SDK version with command `xcrun --show-sdk-version`.

Maybe installing (or reinstalling) certain Xcode components will be necessary ... Anyway, if you don't bring your development environment into a proper shape, you'll be continuously heading for trouble later on.

**Comment by liaoxuewei** [comment]
It show 10.11...

**Comment by utelle** [comment]
Well, I really don't know what to make out of this. Since I don't know the Mac OS X toolchain and don't have direct access to a Mac OS X system, it is almost impossible for me to assist you in sorting things out. For sure there is a way to explicitly request the Mac OS X 10.11 SDK on building an application with Xcode. Are you sure, the Mac OS X 10.11 SDK is actually used when building your application? You should inspect the Xcode build log to hopefully find this out. Maybe [this link](https://stackoverflow.com/questions/30060898/xcode-how-to-see-build-command-and-log) can help.

I would recommend that you seek for advice among Mac OS X developers, for example [here](https://www.techrepublic.com/forums/mac-os/), a Mac OS X Tech forum - probably not the only one of its kind.

**Comment by utelle** [comment]
AFAICT this issue is related to a somewhat outdated (and possibly misconfigured) Mac OS X development environment. Therefore I'm closing this issue.

Feel free to reopen it, if you can come up with new information.
