### ISSUE TITLE
error: unknown type name 'DIR'

### ISSUE THREAD

**Issue by FestusHagen** [utelle/wxsqlite3#23]
Hi All,

MinGW reports the following error:

```"==== Building wxsqlite3 (debug_x32) ===="
Creating ../lib/gcc_lib
sqlite3secure.c
In file included from ../sqlite3/secure/src/sqlite3secure.c:117:0:
../sqlite3/secure/src/fileio.c: In function 'writefileFunc':
../sqlite3/secure/src/fileio.c:356:9: warning: implicit declaration of function 'S_ISLNK' [-Wimplicit-function-declaration]
     if( S_ISLNK(mode) ){
         ^
../sqlite3/secure/src/fileio.c: At top level:
../sqlite3/secure/src/fileio.c:410:3: error: unknown type name 'DIR'
   DIR *pDir;                 /* From opendir() */
   ^
../sqlite3/secure/src/fileio.c: In function 'fsdirResetCursor':
../sqlite3/secure/src/fileio.c:490:22: warning: implicit declaration of function 'closedir' [-Wimplicit-function-declaration]
     if( pLvl->pDir ) closedir(pLvl->pDir);
                      ^
../sqlite3/secure/src/fileio.c: In function 'fsdirNext':
../sqlite3/secure/src/fileio.c:552:18: warning: implicit declaration of function 'opendir' [-Wimplicit-function-declaration]
     pLvl->pDir = opendir(pLvl->zDir);
                  ^
../sqlite3/secure/src/fileio.c:552:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     pLvl->pDir = opendir(pLvl->zDir);
                ^
../sqlite3/secure/src/fileio.c:561:29: warning: implicit declaration of function 'readdir' [-Wimplicit-function-declaration]
     struct dirent *pEntry = readdir(pLvl->pDir);
                             ^
../sqlite3/secure/src/fileio.c:561:29: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
../sqlite3/secure/src/fileio.c:563:17: error: dereferencing pointer to incomplete type 'struct DIRENT'
       if( pEntry->d_name[0]=='.' ){
                 ^
wxsqlite3.make:411: recipe for target 'obj/x32/Debug/wxsqlite3/sqlite3secure.o' failed
mingw32-make[1]: *** [obj/x32/Debug/wxsqlite3/sqlite3secure.o] Error 1
Makefile:82: recipe for target 'wxsqlite3' failed
mingw32-make: *** [wxsqlite3] Error 2```

-Enjoy

**Comment by utelle** [comment]
I tested to compile wxSQLite3 with TDM-GCC 5.1. And that worked flawlessly.

Which MinGW version are you using? Probably the compiler is not detected correctly in the newly added SQLite3 header file `test_windirent.h` for your compiler, while it works for TDM-GCC 5.1.

**Comment by FestusHagen** [comment]
```
>gcc --version
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by utelle** [comment]
I will try to find out how the issue can be fixed. However, I can't promise anything, since I don't intend to install yet another compiler.

For the time being try to remove the compile time symbol `SQLITE_ENABLE_FILEIO`.

**Comment by utelle** [comment]
Well, I took the time to install a current 32-bit MinGW system (my development system still runs on a 32-bit virtual machine):
```
>gcc --version
gcc (MinGW.org GCC-6.3.0-1) 6.3.0

Compiling the underlying SQLite3 library works for me flawlessly without changing anything.

**Comment by utelle** [comment]
I found out that the SQLite3 shell includes/defines some MinGW specifics that obviously influence the compilation of the fileio extension.

Please check whether the patch to file `sqlite3secure.c` fixes the problem for you.

**Comment by FestusHagen** [comment]
So close ...
```"==== Building wxsqlite3 (debug_x32) ===="
Creating ../lib/gcc_lib
Creating obj/x32/Debug/wxsqlite3
sqlite3secure.c
wxsqlite3.cpp
wxsqlite3_version.rc
Linking wxsqlite3
"==== Building minimal (debug_x32) ===="
Creating bin/x32/Debug
Creating obj/x32/Debug/minimal
minimal.cpp
minimal.rc
Linking minimal
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxbase31ud.a(baselib_filename.o): In function `ZNK10wxFileName17GetShortcutTargetERK8wxStringRS0_PS0_':
T:\wxWidgets\wxWidgets\build\msw/../../src/common/filename.cpp:1636: undefined reference to `IID_IShellLinkW'
T:\wxWidgets\wxWidgets\build\msw/../../src/common/filename.cpp:1641: undefined reference to `IID_IPersistFile'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxbase31ud.a(baselib_dlmsw.o): In function `GetFileVersion':
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/dlmsw.cpp:67: undefined reference to `GetFileVersionInfoSizeW@8'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/dlmsw.cpp:71: undefined reference to `GetFileVersionInfoW@16'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/dlmsw.cpp:75: undefined reference to `VerQueryValueW@16'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_utilsgui.o): In function `Z28wxEnableFileNameAutoCompleteP6HWND__':
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/utilsgui.cpp:268: undefined reference to `_imp__SHAutoComplete@8'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_window.o): In function `ZN8wxWindow16MSWHandleMessageEPljjl':
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:3273: undefined reference to `IID_IAccessible'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:3273: undefined reference to `LresultFromObject@12'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_window.o): In function `ZN8wxWindow11HandlePowerEjlPb':
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:4172: undefined reference to `wxEVT_POWER_SUSPENDING'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:4176: undefined reference to `wxEVT_POWER_SUSPEND_CANCEL'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:4180: undefined reference to `wxEVT_POWER_SUSPENDED'
T:\wxWidgets\wxWidgets\build\msw/../../src/msw/window.cpp:4184: undefined reference to `wxEVT_POWER_RESUME'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_window.o): In function `ZN12wxPowerEventC1Ei':
T:\wxWidgets\wxWidgets\build\msw/../../include/wx/power.h:54: undefined reference to `vtable for wxPowerEvent'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_window.o): In function `ZN12wxPowerEventD1Ev':
T:\wxWidgets\wxWidgets\build\msw/../../include/wx/power.h:48: undefined reference to `vtable for wxPowerEvent'
T:\wxWidgets\wxWidgets/lib/gcc_lib/libwxmsw31ud_core.a(corelib_msw_textctrl.o):textctrl.cpp:(.data+0x4): undefined reference to `IID_IUnknown'```

**Comment by utelle** [comment]
Sorry, none of the undefined references is related to wxSQLite3, but to the wxWidgets library.

It seems you are linking against a static wxWidgets library. Maybe some additional link libraries for Windows system DLLs are required, but this wouldn't explain the undefined references to wxPowerEvent, wxEVT_POWER_SUSPENDED and the like.

Please check the list of link libraries you use to succesfully compile and link a wxWidgets application (i.e. one of the wxWidgets samples) and compare the list with the one used for building wxSQLite3. Maybe this helps to find out which libaries are possibly missing or whether the link order is possibly wrong.

However, as said for me all works using TDM-GCC 5.1.

**Comment by FestusHagen** [comment]
Our wxWidgets installation works fine, static or dynamic, debug or release.
SQLite3 is also in use around here ...  Not with wxWidgets though.

And yes, wxSqlite3 is most definitely trying to link against static wxWidgets libraries, that is where wxSqlite3 is looking!

With one modification to wxSqlite3 config.gcc:
  `wxCompilerPrefix ?= gcc510TDM` -> `wxCompilerPrefix ?= gcc`
wxSqlite3 is looking for wxWidgets in
  `$(wxRootDir)/lib/$(wxCompilerPrefix)$(wxArchSuffix)_lib`.

That equates to `$(WXWIN)/lib/gcc_lib`.

That is where wxWidgets puts it's static libraries.
It's dynamic libraries are placed in `$(WXWIN)/lib/$(COMPILER)_dll`.

**Comment by utelle** [comment]
I believe you that your wxWidgets installation works fine. However, if you don't check the list of link libraries you have to use to make your own applications link and work correctly if using a static wxWidgets build, and provide this information, I can't help you further.

Which build of wxWidgets is used by the wxSQLite3 makefile is selected by supplying the appropriate config parameter. For example, `config=debug_wxdll_x32` would build a static wxSQLite3 library linking against a shared wxWidgets build.

**Comment by FestusHagen** [comment]
Please explain how `"check the list of link libraries"` ...

**Comment by utelle** [comment]
The wxSQLite3 makefile uses a list of link libraries similar to the following (depends on whether you make a release or debug build):
```
-lwxbase31u -lwxmsw31u_core -lwxjpeg -lwxpng -lwxzlib -lwxtiff -lwxexpat -lwxregex
-lcomctl32 -lrpcrt4 -lshell32 -lgdi32 -lkernel32 -luser32 -lcomdlg32 -lole32 -loleaut32 -ladvapi32
```
That is, the build depends on the wxWidgets base and core library (which themselves depend on several wxWidgets utility libraries). And then you have several Windows system libraries.

The list of link libraries for one of your wxWidgets applications you successfully built will probably look different. Either it includes additional libraries or the order is different or both. Checking these differences might help to find out what's going wrong in your development environment.

**Comment by FestusHagen** [comment]
Is this what you need ... this is from a simple application that is built statically.
Meaning it is a single (fat) .EXE and requires no dll's.

wxWidgets/lib/gcc_lib/libwxmsw31u_core.a wxWidgets/lib/gcc_lib/libwxbase31u.a wxWidgets/lib/gcc_lib/libwxmsw31u_richtext.a wxWidgets/lib/gcc_lib/libwxmsw31u_html.a wxWidgets/lib/gcc_lib/libwxbase31u_xml.a wxWidgets/lib/gcc_lib/libwxmsw31u_adv.a wxWidgets/lib/gcc_lib/libwxmsw31u_aui.a wxWidgets/lib/gcc_lib/libwxpng.a wxWidgets/lib/gcc_lib/libwxtiff.a wxWidgets/lib/gcc_lib/libwxjpeg.a wxWidgets/lib/gcc_lib/libwxzlib.a wxWidgets/lib/gcc_lib/libwxregexu.a wxWidgets/lib/gcc_lib/libwxexpat.a -lwinmm -lcomctl32 -loleacc -lrpcrt4 -lshlwapi -lversion -lwsock32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

**Comment by utelle** [comment]
Yes, this link library list allowed to analyze why you experienced link problems for the static build.

The dynamic build is not affected, since the Windows system libraries are not directly referenced. Of course you need the wxWidgets DLLs at a location known to the system loader (i.e. local directory or entry in the PATH environment variable).

I adjusted the gmake build files. Please give them a try to check whether your link problem is fixed by this adjustment.

**Comment by FestusHagen** [comment]
That works ...

Thank you for your diligence.

-Enjoy
fh : )_~
